coverage:
  status:
    project:
      python:
        target: 95%
        flags: python

    patch:
      python:
        target: 90%
        flags: python

fixes:
  # Codecov expects paths to be relative to the root. See 
  # https://docs.codecov.io/docs/fixing-paths
  - "::python/"
