version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      - checkout
      - run:
          name: Install dependencies and set path
          command: |
            pip install --user -r python/requirements/development.txt
            sudo apt-get install ninja-build libcunit1-dev valgrind clang
            pip install meson --user
            echo 'export PATH=/home/circleci/.local/bin:$PATH' >> $BASH_ENV
      - run:
          name: Compile Python
          command: |
            cd python 
            CFLAGS="--coverage -Wall -Wextra -Werror -Wno-unused-parameter" \
              python setup.py build_ext --inplace
      - run:
          name: Lint Python
          command: |
            cd python
            flake8 --max-line-length 89 kastore setup.py tests
      - run:
          name: Run Python tests 
          command: |
            PYTHONPATH=python nosetests -v --with-coverage --cover-package kastore \
              --cover-branches --cover-erase --cover-xml \
              --cover-inclusive python/tests
            python3 -m codecov -F python
      - run:
          name: Compile C
          command: |
            CFLAGS=--coverage meson c/ build-gcc && cd build-gcc && ninja
      - run:
          name: Run C tests
          command: |
            ./build-gcc/tests
            ./build-gcc/malloc_tests
      - run:
          name: Valgrind for C tests.
          command: |
            valgrind --leak-check=full --error-exitcode=1 ./build-gcc/tests
            valgrind --leak-check=full --error-exitcode=1 ./build-gcc/malloc_tests
      - run:
          name: Run gcov & upload coverage.
          command: |
            gcov -pb -o ./python/build/temp.linux*/ python/_kastoremodule.c
            gcov -pb ./build-gcc/tests@exe/kastore.c.gcno ./build-gcc/malloc_tests@exe/kastore.c.gcno
            codecov -X gcov -F C
      - run:
          name: Compile C tests under clang
          command: |
            CC=clang meson c/ build-clang && cd build-clang && ninja
      - run:
          name: Run clang C tests
          command: |
            ./build-clang/tests
            ./build-clang/malloc_tests
